#include "main.h"

//AUTONOMOUS PID TUNING CONSTANTS
////TRANSLATION CONSTANTS
const double TRANSLATIONAL_MINIMUM_DERIVATIVE = 0.1;
const int TRANSLATIONAL_DERIVATIVE_EXIT = 5;
////ROTATIONAL CONSTANTS
const double ROTATIONAL_MINIMUM_DERIVATIVE = 0.1;
const int ROTATIONAL_ERROR_EXIT = 15;
const int ROTATIONAL_DERIVATIVE_EXIT = 30;

//SPECIAL BOOLEANS
bool ALWAYS_TRUE = true;

//CONVERSION CONSTANTS
const double MILLIMETERS_TO_INCHES= 0.0393701;

//DURATION CONSTANTS
//https://www.vexforum.com/t/v5-distance-sensor-technical-details/88482/8
//DISTANCE SENSOR FREQUENCY IS ~30 HZ: jpearman
const int WHILE_LOOP_DELAY_DURATION = 10;
const int DISTANCE_SENSOR_DELAY = 40;

//MOTOR CONSTANTS
const int MAX_VOLTAGE = 127;
const int NUMBER_OF_MOTORS = 6;

//PRECISION CONSTANTS
const int ANALOG_DEAD_ZONE = 20;
const int ROTATION_PRECISION = 1;
const int TRANSLATION_PRECISION = 5;