#include "main.h"

//DURATION CONSTANTS
const int WHILE_LOOP_DELAY_DURATION = 10;

//MOTOR CONSTANTS
const int MAX_VOLTAGE = 127;
const int NUMBER_OF_MOTORS = 6;

//PRECISION CONSTANTS
const int ANALOG_DEAD_ZONE = 20;
const int ROTATION_PRECISION = 1;
const int TRANSLATION_PRECISION = 5;
const double TRANSLATION_ERROR_CORRECTION_MULTIPLIER = 1;
const double TRANSLATION_ERROR_CLAMP_MINIMUM = 0.9;
const double TRANSLATION_ERROR_CLAMP_MAXIMUM = 1.0;




