#include "main.h"

//CONVERSION CONSTANTS
const double MILLIMETERS_TO_INCHES= 0.0393701;

//DURATION CONSTANTS
const int WHILE_LOOP_DELAY_DURATION = 10;

//MOTOR CONSTANTS
const int MAX_VOLTAGE = 127;
const int NUMBER_OF_MOTORS = 6;

//PRECISION CONSTANTS
const int ANALOG_DEAD_ZONE = 20;
const int ROTATION_PRECISION = 1;
const int TRANSLATION_PRECISION = 5;





